# Generated by Django 4.2.8 on 2023-12-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_candle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
